name: Claim/Unclaim File

on:
  issue_comment:
    types: [created]

jobs:
  manage-claim:
    if: github.event.issue.number == 5
    runs-on: ubuntu-latest
    steps:
      - name: Parse command
        id: parse
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.comment.body.trim();
            core.info(`收到评论: "${body}"`);

            let action = null;
            let file = null;

            // 匹配 \claim 和 \unclaim
            let claimMatch = body.match(/^\\claim\s+(.+)$/);
            let unclaimMatch = body.match(/^\\unclaim\s+(.+)$/);

            if (claimMatch) {
              action = "claim";
              file = claimMatch[1].trim();
              core.info(`解析到命令: claim ${file}`);
            } else if (unclaimMatch) {
              action = "unclaim";
              file = unclaimMatch[1].trim();
              core.info(`解析到命令: unclaim ${file}`);
            } else {
              core.info("未匹配到有效命令，跳过。");
              core.setOutput("do", "false");
              return;
            }

            core.setOutput("do", "true");
            core.setOutput("action", action);
            core.setOutput("file", file);

      - name: Process claim/unclaim
        if: steps.parse.outputs.do == 'true'
        id
